import type {
  Tag,
  Contact,
  Property,
  MessageTemplate,
  CallLog,
  MarketingExpense,
  Cheque,
  AgendaTask,
  Appointment,
} from "./types";

// ─────────────────────────────────────────────────────────────
// MOCK DATA — fully testable without any external API.
// Mirrors the Supabase schema in /supabase/migrations.
// ─────────────────────────────────────────────────────────────

export const TAGS: Tag[] = [
  { id: "t-balcony", label: "#BigBalcony", color: "teal", kind: "physical" },
  { id: "t-penthouse", label: "#Penthouse", color: "violet", kind: "physical" },
  { id: "t-garden", label: "#GardenApt", color: "green", kind: "physical" },
  { id: "t-commercial", label: "#Commercial", color: "amber", kind: "physical" },
  { id: "t-renovated", label: "#Renovated", color: "blue", kind: "physical" },
  { id: "t-parking", label: "#Parking", color: "slate", kind: "physical" },
  { id: "t-investment", label: "#Investment", color: "rose", kind: "behavioral" },
  { id: "t-urgent", label: "#Urgent", color: "red", kind: "behavioral" },
  { id: "t-budget25", label: "#BudgetUnder2.5M", color: "emerald", kind: "financial" },
  { id: "t-budget4", label: "#BudgetUnder4M", color: "cyan", kind: "financial" },
  { id: "t-beeryaakov", label: "#BeerYaakov", color: "indigo", kind: "location" },
  { id: "t-rishon", label: "#RishonLezion", color: "fuchsia", kind: "location" },
  { id: "t-telaviv", label: "#TelAviv", color: "orange", kind: "location" },
];

export const tagById = (id: string) => TAGS.find((t) => t.id === id);

export const CONTACTS: Contact[] = [
  {
    id: "c-1",
    type: "seller",
    name: "David Cohen",
    phone: "+972-52-555-1212",
    email: "david.cohen@example.com",
    city: "Beer Yaakov",
    stage: "active",
    seriousness: "hot",
    source: "Yad2 Scraper",
    tags: ["t-penthouse", "t-beeryaakov", "t-urgent"],
    dncFlagged: false,
    createdAt: "2026-03-02",
    lastContactedAt: "2026-06-22",
    notes: "Wants to sell quickly, relocating abroad.",
    propertyId: "p-1",
  },
  {
    id: "c-2",
    type: "buyer",
    name: "Maya Levi",
    phone: "+972-54-777-3434",
    email: "maya.levi@example.com",
    city: "Rishon Lezion",
    stage: "active",
    seriousness: "hot",
    source: "Facebook Ad",
    tags: ["t-balcony", "t-budget25"],
    dncFlagged: false,
    createdAt: "2026-05-11",
    lastContactedAt: "2026-06-24",
    budgetMin: 1800000,
    budgetMax: 2500000,
    preferredCities: ["Rishon Lezion", "Beer Yaakov"],
    desiredTags: ["t-balcony", "t-renovated"],
    rooms: 4,
  },
  {
    id: "c-3",
    type: "buyer",
    name: "Yossi Mizrahi",
    phone: "+972-50-222-9000",
    city: "Tel Aviv",
    stage: "active",
    seriousness: "warm",
    source: "Sign",
    tags: ["t-penthouse", "t-budget4", "t-investment"],
    dncFlagged: true, // hit the DNC registry (ends in 000)
    createdAt: "2026-04-18",
    lastContactedAt: "2026-06-10",
    budgetMin: 2800000,
    budgetMax: 4000000,
    preferredCities: ["Tel Aviv", "Rishon Lezion"],
    desiredTags: ["t-penthouse", "t-parking"],
    rooms: 5,
  },
  {
    id: "c-4",
    type: "renter",
    name: "Noa Friedman",
    phone: "+972-53-888-4545",
    email: "noa.f@example.com",
    city: "Rishon Lezion",
    stage: "active",
    seriousness: "warm",
    source: "Referral",
    tags: ["t-rishon", "t-garden"],
    dncFlagged: false,
    createdAt: "2025-07-20",
    lastContactedAt: "2026-06-01",
    budgetMin: 5000,
    budgetMax: 7500,
    preferredCities: ["Rishon Lezion"],
    desiredTags: ["t-garden", "t-parking"],
    rooms: 3,
    leaseStartDate: "2025-07-25", // ~11 months ago → renewal trigger
    leaseEndDate: "2026-07-25",
  },
  {
    id: "c-5",
    type: "seller",
    name: "Rina Azoulay",
    phone: "+972-52-111-0007",
    city: "Tel Aviv",
    stage: "past_client",
    seriousness: "cold",
    source: "Referral",
    tags: ["t-telaviv"],
    dncFlagged: true,
    createdAt: "2025-01-15",
    lastContactedAt: "2025-12-20",
    notes: "Deal closed — moved to Past Clients Archive.",
    propertyId: "p-4",
  },
  {
    id: "c-6",
    type: "buyer",
    name: " Benyamin Shapiro",
    phone: "+972-58-444-1199",
    email: "ben.shapiro@example.com",
    city: "Beer Yaakov",
    stage: "nurturing",
    seriousness: "cold",
    source: "Facebook Ad",
    tags: ["t-garden", "t-budget25", "t-beeryaakov"],
    dncFlagged: false,
    createdAt: "2026-02-28",
    lastContactedAt: "2026-05-15",
    budgetMin: 1500000,
    budgetMax: 2300000,
    preferredCities: ["Beer Yaakov"],
    desiredTags: ["t-garden"],
    rooms: 4,
  },
  {
    id: "c-7",
    type: "renter",
    name: "Tamar Golan",
    phone: "+972-54-333-2020",
    city: "Tel Aviv",
    stage: "active",
    seriousness: "warm",
    source: "Yad2 Scraper",
    tags: ["t-telaviv", "t-renovated"],
    dncFlagged: false,
    createdAt: "2026-01-10",
    budgetMin: 6000,
    budgetMax: 9000,
    preferredCities: ["Tel Aviv"],
    desiredTags: ["t-renovated", "t-balcony"],
    rooms: 2,
    leaseStartDate: "2026-01-15",
    leaseEndDate: "2027-01-15",
  },
];

export const PROPERTIES: Property[] = [
  {
    id: "p-1",
    code: "BY-PENT-04",
    title: "Luxury Penthouse · Beer Yaakov",
    address: "12 HaShalom St, Beer Yaakov",
    city: "Beer Yaakov",
    status: "active",
    origin: "internal",
    askingPrice: 3850000,
    rooms: 5,
    sizeSqm: 165,
    exclusive: true,
    tags: ["t-penthouse", "t-balcony", "t-parking", "t-beeryaakov"],
    sellerId: "c-1",
    image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=60",
    brochure: {
      tabuDeed: true,
      municipalTax: true,
      floorPlan: true,
      virtualTour: true,
      comparables: true,
    },
    createdAt: "2026-03-03",
    commissionRate: 2,
  },
  {
    id: "p-2",
    code: "RL-BAL-21",
    title: "4-Room w/ Big Balcony · Rishon",
    address: "45 Rothschild Ave, Rishon Lezion",
    city: "Rishon Lezion",
    status: "active",
    origin: "internal",
    askingPrice: 2390000,
    rooms: 4,
    sizeSqm: 105,
    exclusive: true,
    tags: ["t-balcony", "t-renovated", "t-parking", "t-rishon"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    brochure: {
      tabuDeed: true,
      municipalTax: true,
      floorPlan: true,
      virtualTour: false,
      comparables: true,
    },
    createdAt: "2026-04-21",
    commissionRate: 2,
  },
  {
    id: "p-3",
    code: "BY-GRD-09",
    title: "Garden Apartment · Beer Yaakov",
    address: "8 Herzl St, Beer Yaakov",
    city: "Beer Yaakov",
    status: "under_offer",
    origin: "proptech_feed",
    askingPrice: 2150000,
    rooms: 4,
    sizeSqm: 110,
    exclusive: false,
    tags: ["t-garden", "t-parking", "t-beeryaakov"],
    image:
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=60",
    brochure: {
      tabuDeed: true,
      municipalTax: false,
      floorPlan: true,
      virtualTour: true,
      comparables: false,
    },
    createdAt: "2026-05-30",
    commissionRate: 2,
  },
  {
    id: "p-4",
    code: "TA-PENT-01",
    title: "Penthouse · Tel Aviv (SOLD)",
    address: "100 Dizengoff St, Tel Aviv",
    city: "Tel Aviv",
    status: "sold",
    origin: "internal",
    askingPrice: 6200000,
    soldPrice: 6050000,
    rooms: 5,
    sizeSqm: 180,
    exclusive: true,
    tags: ["t-penthouse", "t-balcony", "t-telaviv"],
    sellerId: "c-5",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    brochure: {
      tabuDeed: true,
      municipalTax: true,
      floorPlan: true,
      virtualTour: true,
      comparables: true,
    },
    createdAt: "2025-02-01",
    commissionRate: 2,
  },
  {
    id: "p-5",
    code: "TA-COM-15",
    title: "Commercial Unit · Tel Aviv",
    address: "22 Allenby St, Tel Aviv",
    city: "Tel Aviv",
    status: "active",
    origin: "proptech_feed",
    askingPrice: 3950000,
    rooms: 3,
    sizeSqm: 95,
    exclusive: false,
    tags: ["t-commercial", "t-telaviv", "t-investment"],
    image:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=60",
    brochure: {
      tabuDeed: true,
      municipalTax: true,
      floorPlan: false,
      virtualTour: false,
      comparables: true,
    },
    createdAt: "2026-06-12",
    commissionRate: 2,
  },
];

export const MESSAGE_TEMPLATES: MessageTemplate[] = [
  {
    id: "tpl-1",
    name: "new_listing_match",
    category: "marketing",
    language: "en",
    body: "Hi {{name}}! 🏡 A new property matching your search just hit the market: {{1}}. Want a private viewing? Reply YES.",
    status: "approved",
  },
  {
    id: "tpl-2",
    name: "viewing_reminder",
    category: "utility",
    language: "en",
    body: "Reminder: your viewing at {{1}} is on {{2}}. Confirm here: {{3}}",
    status: "approved",
  },
  {
    id: "tpl-3",
    name: "seller_acquisition",
    category: "marketing",
    language: "he",
    body: "שלום {{name}}, ראינו שפרסמת נכס למכירה. נשמח להציע פגישת הערכת שווי ללא עלות. מתי נוח?",
    status: "approved",
  },
  {
    id: "tpl-4",
    name: "lease_renewal_11mo",
    category: "utility",
    language: "en",
    body: "Hi {{name}}, your lease ends soon. Shall we renew or find you a new place? Let's talk!",
    status: "approved",
  },
  {
    id: "tpl-5",
    name: "holiday_greeting",
    category: "marketing",
    language: "he",
    body: "{{name}} יקר/ה, חג שמח מכל הצוות! 🎉",
    status: "pending",
  },
];

export const CALL_LOGS: CallLog[] = [
  {
    id: "call-1",
    contactId: "c-2",
    direction: "outbound",
    durationSec: 312,
    timestamp: "2026-06-24T09:15:00",
    recordingUrl: "/api/recording/call-1",
    dncChecked: true,
    outcome: "connected",
  },
  {
    id: "call-2",
    contactId: "c-1",
    direction: "inbound",
    durationSec: 540,
    timestamp: "2026-06-22T14:30:00",
    recordingUrl: "/api/recording/call-2",
    dncChecked: true,
    outcome: "connected",
  },
  {
    id: "call-3",
    contactId: "c-3",
    direction: "outbound",
    durationSec: 0,
    timestamp: "2026-06-10T11:00:00",
    recordingUrl: "/api/recording/call-3",
    dncChecked: true,
    outcome: "no_answer",
  },
  {
    id: "call-4",
    contactId: "c-4",
    direction: "inbound",
    durationSec: 128,
    timestamp: "2026-06-01T16:45:00",
    recordingUrl: "/api/recording/call-4",
    dncChecked: true,
    outcome: "connected",
  },
];

export const MARKETING_EXPENSES: MarketingExpense[] = [
  { id: "e-1", propertyId: "p-1", category: "facebook_ads", label: "Meta Lead Campaign", amount: 4200, date: "2026-03-10" },
  { id: "e-2", propertyId: "p-1", category: "photography", label: "Pro Photo + Drone", amount: 1800, date: "2026-03-05" },
  { id: "e-3", propertyId: "p-1", category: "signage", label: "Balcony Banner", amount: 600, date: "2026-03-04" },
  { id: "e-4", propertyId: "p-2", category: "facebook_ads", label: "Instagram Boost", amount: 2100, date: "2026-04-25" },
  { id: "e-5", propertyId: "p-2", category: "staging", label: "Home Staging", amount: 3500, date: "2026-04-22" },
  { id: "e-6", propertyId: "p-4", category: "facebook_ads", label: "Premium Campaign", amount: 7800, date: "2025-02-10" },
  { id: "e-7", propertyId: "p-4", category: "photography", label: "Luxury Shoot", amount: 3200, date: "2025-02-05" },
];

export const CHEQUES: Cheque[] = [
  { id: "chq-1", propertyId: "p-4", clientName: "Rina Azoulay", amount: 121000, dueDate: "2026-07-01", status: "pending", direction: "incoming" },
  { id: "chq-2", propertyId: "p-1", clientName: "David Cohen (deposit)", amount: 38500, dueDate: "2026-07-15", status: "pending", direction: "incoming" },
  { id: "chq-3", clientName: "Office Rent", amount: 9000, dueDate: "2026-07-01", status: "pending", direction: "outgoing" },
  { id: "chq-4", propertyId: "p-4", clientName: "Rina Azoulay", amount: 60000, dueDate: "2026-05-01", status: "cleared", direction: "incoming" },
  { id: "chq-5", clientName: "Photographer Vendor", amount: 3200, dueDate: "2026-06-20", status: "cleared", direction: "outgoing" },
];

const today = new Date();
const iso = (d: Date) => d.toISOString().slice(0, 10);
const shift = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return iso(d);
};

export const AGENDA_TASKS: AgendaTask[] = [
  { id: "task-1", title: "Call David Cohen re: penthouse offer", contactId: "c-1", dueDate: shift(0), status: "pending", priority: "high", syncedToCalendar: true },
  { id: "task-2", title: "Send brochure BY-PENT-04 to Maya", contactId: "c-2", dueDate: shift(0), status: "pending", priority: "high", syncedToCalendar: true },
  { id: "task-3", title: "Follow up Yossi Mizrahi", contactId: "c-3", dueDate: shift(-1), status: "rolled_over", rolledFrom: shift(-1), priority: "medium", syncedToCalendar: true },
  { id: "task-4", title: "Order signage for RL-BAL-21", dueDate: shift(-2), status: "rolled_over", rolledFrom: shift(-2), priority: "low", syncedToCalendar: false },
  { id: "task-5", title: "Prepare CMA report for new seller", dueDate: shift(0), status: "done", priority: "medium", syncedToCalendar: true },
  { id: "task-6", title: "Renewal call — Noa Friedman lease", contactId: "c-4", dueDate: shift(1), status: "pending", priority: "high", syncedToCalendar: true },
  { id: "task-7", title: "Confirm photographer for Garden Apt", dueDate: shift(2), status: "pending", priority: "medium", syncedToCalendar: true },
];

export const APPOINTMENTS: Appointment[] = [
  {
    id: "appt-1",
    propertyId: "p-1",
    contactId: "c-2",
    scheduledAt: shift(1) + "T17:00:00",
    status: "confirmed",
    wazeUrl: "https://waze.com/ul?q=12%20HaShalom%20St%20Beer%20Yaakov",
    confirmationToken: "tok-appt-1",
  },
  {
    id: "appt-2",
    propertyId: "p-2",
    contactId: "c-6",
    scheduledAt: shift(2) + "T11:30:00",
    status: "pending",
    wazeUrl: "https://waze.com/ul?q=45%20Rothschild%20Ave%20Rishon%20Lezion",
    confirmationToken: "tok-appt-2",
  },
  {
    id: "appt-3",
    propertyId: "p-3",
    contactId: "c-6",
    scheduledAt: shift(3) + "T18:15:00",
    status: "pending",
    wazeUrl: "https://waze.com/ul?q=8%20Herzl%20St%20Beer%20Yaakov",
    confirmationToken: "tok-appt-3",
  },
];

// Helper lookups
export const contactById = (id: string) => CONTACTS.find((c) => c.id === id);
export const propertyById = (id: string) => PROPERTIES.find((p) => p.id === id);
export const propertyByCode = (code: string) =>
  PROPERTIES.find((p) => p.code.toLowerCase() === code.toLowerCase());
